package data;
// Generated 2014-11-22 00:30:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Loginhistory generated by hbm2java
 */
public class Loginhistory  implements java.io.Serializable {


     private int id;
     private int idftpuser;
     private Date logintime;
     private int idoperation;
     private int idoperationstatus;
     private Date datetime;

    public Loginhistory() {
    }

	
    public Loginhistory(int id, int idftpuser, int idoperation, int idoperationstatus) {
        this.id = id;
        this.idftpuser = idftpuser;
        this.idoperation = idoperation;
        this.idoperationstatus = idoperationstatus;
    }
    public Loginhistory(int id, int idftpuser, Date logintime, int idoperation, int idoperationstatus, Date datetime) {
       this.id = id;
       this.idftpuser = idftpuser;
       this.logintime = logintime;
       this.idoperation = idoperation;
       this.idoperationstatus = idoperationstatus;
       this.datetime = datetime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdftpuser() {
        return this.idftpuser;
    }
    
    public void setIdftpuser(int idftpuser) {
        this.idftpuser = idftpuser;
    }
    public Date getLogintime() {
        return this.logintime;
    }
    
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }
    public int getIdoperation() {
        return this.idoperation;
    }
    
    public void setIdoperation(int idoperation) {
        this.idoperation = idoperation;
    }
    public int getIdoperationstatus() {
        return this.idoperationstatus;
    }
    
    public void setIdoperationstatus(int idoperationstatus) {
        this.idoperationstatus = idoperationstatus;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


