package data;
// Generated 2014-11-16 20:23:20 by Hibernate Tools 4.3.1



/**
 * Operation generated by hbm2java
 */
public class Operation  implements java.io.Serializable {


     private int id;
     private String operationname;
     private String description;

    public Operation() {
    }

	
    public Operation(int id, String operationname) {
        this.id = id;
        this.operationname = operationname;
    }
    public Operation(int id, String operationname, String description) {
       this.id = id;
       this.operationname = operationname;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getOperationname() {
        return this.operationname;
    }
    
    public void setOperationname(String operationname) {
        this.operationname = operationname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


