/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.przemo.ballsgame;

import com.przmnwck.games.ballsengine.BoardException;
import com.przmnwck.games.ballsengine.Engine;
import com.przmnwck.games.ballsengine.EngineEvent;
import com.przmnwck.games.ballsengine.EngineStartException;
import com.przmnwck.games.ballsengine.EngineState;
import com.przmnwck.games.ballsengine.interfaces.IEngineListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Przemo
 */
public class SettingsPanel extends javax.swing.JPanel {

    private int np, bs, ap;

    List<IEngineListener> engListeners = null;
    
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
        engListeners = new ArrayList<IEngineListener>();
        fillSymbolsList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSymbols = new javax.swing.JList();
        txtNoPlayers = new javax.swing.JTextField();
        txtBoardSize = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();

        jLabel1.setText("No. of Players");

        jLabel2.setText("Board size");

        jLabel3.setText("Pick your symbol");

        lstSymbols.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstSymbols);

        txtNoPlayers.setEditable(false);
        txtNoPlayers.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNoPlayers.setText("2");

        txtBoardSize.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBoardSize.setText("3");

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBoardSize)
                            .addComponent(txtNoPlayers)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPlay)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNoPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtBoardSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void fillSymbolsList(){
            lstSymbols.setListData(App.sh);
            lstSymbols.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:       
        try {
            if (validateEntry()) {
                EngineEvent evtx = new EngineEvent(new Engine(np, bs, ap));
                evtx.setState(EngineState.INIT);
                for(IEngineListener el: engListeners){
                    el.stateChanged(evtx);
                }
            }
        } catch (BoardException ex) {
        } catch (EngineStartException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Engine error", JOptionPane.ERROR);
            Logger.getLogger(SettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(-1);
        } 
    }//GEN-LAST:event_btnPlayActionPerformed

    protected boolean validateEntry() throws BoardException{
        try{
            np=Integer.parseInt(txtNoPlayers.getText());
            bs=Integer.parseInt(txtBoardSize.getText());
            //pick first free slot from the symbols
            int ix=0;
            while(ix < lstSymbols.getModel().getSize() && lstSymbols.isSelectedIndex(ix)){
                ix++;
            }
            if(ix>lstSymbols.getModel().getSize()){
                ap=0;
            } else {
                ap=ix+1;
            }
            return true;
        } catch(NumberFormatException ex){
            return false;
        }
    }
    
    public void addListener(IEngineListener l){
        if(engListeners!=null && !engListeners.contains(l)){
            engListeners.add(l);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstSymbols;
    private javax.swing.JTextField txtBoardSize;
    private javax.swing.JTextField txtNoPlayers;
    // End of variables declaration//GEN-END:variables
}
